REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE roas_radar FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT CONNECT ON DATABASE roas_radar TO roas_app;
GRANT CONNECT ON DATABASE roas_radar TO roas_migrator;
GRANT CONNECT ON DATABASE roas_radar TO roas_readonly;

GRANT USAGE ON SCHEMA public TO roas_app;
GRANT USAGE ON SCHEMA public TO roas_readonly;
GRANT CREATE ON SCHEMA public TO roas_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE roas_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO roas_app;

ALTER DEFAULT PRIVILEGES FOR ROLE roas_migrator IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO roas_app;

ALTER DEFAULT PRIVILEGES FOR ROLE roas_migrator IN SCHEMA public
  GRANT SELECT ON TABLES TO roas_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE roas_migrator IN SCHEMA public
  GRANT SELECT ON SEQUENCES TO roas_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO roas_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO roas_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO roas_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO roas_readonly;

ALTER SCHEMA public OWNER TO roas_migrator;
