gcloud run jobs deploy "$META_ADS_JOB_NAME" \
  --args=run,meta-ads:sync:start \
  --set-env-vars="${COMMON_ENV_VARS}@DATABASE_POOL_MAX=$ADS_SYNC_DATABASE_POOL_MAX@META_ADS_WORKER_LOOP=false@META_ADS_JOB_MODE=spend"

gcloud run jobs deploy "$META_ADS_ORDER_VALUE_JOB_NAME" \
  --args=run,meta-ads:order-value:start \
  --set-env-vars="${COMMON_ENV_VARS}@DATABASE_POOL_MAX=$ADS_SYNC_DATABASE_POOL_MAX@META_ADS_JOB_MODE=order_value@META_ADS_ORDER_VALUE_SYNC_ENABLED=$META_ADS_ORDER_VALUE_SYNC_ENABLED@META_ADS_ORDER_VALUE_SYNC_INTERVAL_MS=$META_ADS_ORDER_VALUE_SYNC_INTERVAL_MS@META_ADS_ORDER_VALUE_WINDOW_DAYS=$META_ADS_ORDER_VALUE_WINDOW_DAYS@META_ADS_ORDER_VALUE_ANOMALY_MIN_ROWS=$META_ADS_ORDER_VALUE_ANOMALY_MIN_ROWS@META_ADS_ORDER_VALUE_NULL_SPIKE_MIN_RATIO=$META_ADS_ORDER_VALUE_NULL_SPIKE_MIN_RATIO@META_ADS_ORDER_VALUE_NULL_SPIKE_RATIO_DELTA=$META_ADS_ORDER_VALUE_NULL_SPIKE_RATIO_DELTA"
