  SHOPIFY_ORDER_WRITEBACK_BATCH_SIZE: integerString.default(25),
  SHOPIFY_ORDER_WRITEBACK_MAX_RETRIES: integerString.default(8),
  SHOPIFY_RECONCILIATION_ENABLED: booleanString.default(true),
  SHOPIFY_RECONCILIATION_LOOKBACK_DAYS: integerString.default(30),
  SHOPIFY_RECONCILIATION_BATCH_SIZE: integerString.default(100),
  SHOPIFY_RECONCILIATION_INTERVAL_MS: integerString.default(6 * 60 * 60 * 1000),
  SHOPIFY_WEBHOOK_SECRET: z.string().optional().default(''),
